### ISSUE TITLE
Android menu touch problem

### ISSUE THREAD

**Issue by dizlexik** [react-native-fellowship/react-native-side-menu#118] opened 2015-10-20 21:05 UTC
I'm building a cross-platform app and have run into an issue with touch events not making it through to my menu component on Android. It works fine on iOS, but on Android any touch on the menu is treated as a touch on the content portion of the screen. For example, when I have `touchToClose` turned on and I tap on my menu it triggers a close. When I use the inspector and click the menu it shows me the path to `App > SideMenu > TouchableWithoutFeedback` on Android, which is strange since it also shows that that is starting at (240, 0) on my (360 x 488) screen and I'm clearly clicking to the left of that. On iOS the inspector works as expected and shows me the path to `App > Menu > MyComponent`. Any ideas as to what may be going on here? Thanks in advance!

**Comment by dizlexik** [comment] 2015-10-22 16:06
Looks like this is probably the issue: facebook/react-native#3201

**Comment by thstarshine** [comment] 2015-10-26 07:56
+1 Haven't figured out why

**Comment by dizlexik** [comment] 2015-10-26 17:24
As a temporary fix I've updated `index.js` on my local copy as follows:
Line 231: `const {width, height, left} = this.state;`
Line 235: `style={[styles.frontView, {width, height, left}]}`

I know it's technically less performant but there's no actual noticeable difference as far as I can tell. It's a good stopgap for now until facebook/react-native#3426 is fixed.

**Comment by mjhlybmwq** [comment] 2015-11-13 03:44
facebook/react-native#3426 is closed but I still got the problem. Any ideas???

**Comment by mjhlybmwq** [comment] 2015-11-13 07:20
I've figured it out and make a PR. Before it's merged, you can solve the issue by set the animationStyle like this: animationStyle={ (value)=>{return {left : value}} }

**Comment by Kureev** [comment] 2015-11-13 13:41
Until we'll have a new RN version with [#3426 issue](https://github.com/facebook/react-native/pull/3426) fixed, I'd propose you to use @mjhlybmwq solution as a workaround. Because of some reasons (you can read about them in PR thread) I don't want to merge it in, but nothing prevents you from using this solution.

**Comment by mjhlybmwq** [comment] 2015-11-25 02:00
Still have this issue after RN upgraded to 0.15

**Comment by Kureev** [comment] 2015-11-25 08:46
@brentvatne maybe you know more about it?

**Comment by Iragne** [comment] 2015-12-01 18:04
RN 0.16 should solved it

**Comment by laeijebor** [comment] 2015-12-02 01:39
Spent a while digging for this issue - would there be any issue with specifying @mjhlybmwq 's solution as the default prop?

**Comment by rmevans9** [comment] 2015-12-07 13:40
Looks like RN closed the linked issue above with 0.16.0 which was released a few days ago. I will test with the latest RN at some point today but figured I would let everyone know that it, in theory, should be working!

**Comment by rmevans9** [comment] 2015-12-08 02:00
Confirmed. This issue should be closed.

**Comment by Kureev** [comment] 2015-12-08 08:40
Closed in `react-native` v0.16

**Closed by Kureev** 2015-12-08 08:40 UTC
Labels: react-native bug
